export const RULE_TYPES = {
    PROHIBITION: "PROHIBITION",
    MANDATORY: "MANDATORY_OBLIGATION",
    NUMERIC_THRESHOLD: "NUMERIC_THRESHOLD",
    TIME_REQUIREMENT: "TIME_REQUIREMENT",
    REGISTRATION_REQUIRED: "REGISTRATION_REQUIRED",
    PENALTY: "PENALTY",
    CONDITIONAL: "CONDITIONAL_TRIGGER"
  };