/**
 * jurisdictionEngine.js
 * 
 * Adapts clauses based on the jurisdiction/operating state.
 * Specifically updates Governing Law and Dispute Resolution seats
 * based on local requirements in India.
 */

export function injectJurisdictionRules(draft, input) {
  if (!draft || !Array.isArray(draft.clauses) || !input) {
    return draft;
  }

  // Extract the state provided by the user in the form variables
  const operatingState = input.variables?.operating_state;
  const arbitrationCity =
    input.variables?.arbitration_city || input.variables?.operating_state;

  if (!operatingState) {
    return draft; // Default rules generated by Base Draft remain
  }

  const modifiedClauses = draft.clauses.map(clause => {
    let newText = clause.text || "";

    // 1. Force the Arbitration Seat to match the Operating State
    if (clause.category === "DISPUTE_RESOLUTION" || clause.category === "ARBITRATION") {
      newText = newText.replace(/courts in [a-zA-Z\s]+|seat of arbitration shall be [a-zA-Z\s]+/gi, match => {
        if (match.toLowerCase().includes("seat")) {
          return `seat of arbitration shall be ${arbitrationCity}`;
        }
        return `courts in ${arbitrationCity}`;
      });
    }

    // 2. Adjust Governing Law text
    if (clause.category === "GOVERNING_LAW") {
      if (!newText.includes("laws of India")) {
        newText = `This Agreement shall be governed by and construed in accordance with the laws of India, as applied in the State of ${operatingState}.`;
      }
    }

    // 3. Stamp Duty Injection (Usually handled in Execution/Signatures block)
    if (clause.category === "SIGNATURES" && !newText.toLowerCase().includes("stamp paper")) {
      newText = `IN WITNESS WHEREOF, the Parties have executed this Agreement on non-judicial stamp paper of appropriate value as per the local stamp act of ${operatingState}.\n\n` + newText;
    }

    return {
      ...clause,
      text: newText
    };
  });

  return {
    ...draft,
    jurisdiction: operatingState,
    clauses: modifiedClauses
  };
}
