/**
 * generateFrontendNotices.mjs
 *
 * Writes frontend/public/third-party-notices.txt: the licence and copyright
 * notice of every package that ships in the frontend bundle (production
 * dependencies, direct and transitive), plus the icon sets whose drawings are
 * copied into frontend/src/utils/icons.jsx. MIT, ISC and BSD all require the
 * notice to travel with the code; the bundle is the code users receive.
 *
 *   node scripts/generateFrontendNotices.mjs          write the file
 *   node scripts/generateFrontendNotices.mjs --check  exit 1 if it is out of date
 */
import fs from "fs";
import path from "path";
import { execFileSync } from "child_process";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const FRONTEND = path.join(ROOT, "frontend");
const OUT = path.join(FRONTEND, "public", "third-party-notices.txt");

function productionPackages() {
  const json = execFileSync("npm", ["ls", "--omit=dev", "--all", "--json"], { cwd: FRONTEND, encoding: "utf8", maxBuffer: 32 * 1024 * 1024 });
  const seen = new Map();
  (function walk(deps = {}) {
    for (const [name, info] of Object.entries(deps)) {
      const key = `${name}@${info.version}`;
      if (!seen.has(key)) seen.set(key, { name, version: info.version });
      walk(info.dependencies);
    }
  })(JSON.parse(json).dependencies);
  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
}

function licenceText(dir) {
  const file = fs.readdirSync(dir).find((f) => /^(licen[cs]e|copying)(\.(md|txt))?$/i.test(f));
  return file ? fs.readFileSync(path.join(dir, file), "utf8").trim() : null;
}

const ICONS = `Lucide icons (drawings copied into frontend/src/utils/icons.jsx)
License: ISC
-----------------------------------------------------------------------------
ISC License

Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as part of Feather (MIT). All other copyright (c) for Lucide are held by Lucide Contributors 2022.

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.


Feather icons (drawings copied into frontend/src/utils/icons.jsx)
License: MIT
-----------------------------------------------------------------------------
The MIT License (MIT)

Copyright (c) 2013-2017 Cole Bemis

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.`;

function render() {
  const parts = [
    "THIRD-PARTY NOTICES — LegalAId web application",
    "",
    "The LegalAId web application includes the open-source software and icon drawings listed below.",
    "Each is used under its own licence, reproduced in full. Generated by scripts/generateFrontendNotices.mjs.",
    "",
    "=============================================================================",
    "",
    ICONS,
  ];
  const missing = [];
  for (const pkg of productionPackages()) {
    const dir = path.join(FRONTEND, "node_modules", pkg.name);
    const meta = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
    const licence = typeof meta.license === "string" ? meta.license : meta.license?.type || (meta.licenses || []).map((l) => l.type).join(" OR ") || "UNKNOWN";
    const text = licenceText(dir);
    if (!text) missing.push(pkg.name);
    parts.push("", "", `${pkg.name} ${pkg.version}`, `License: ${licence}`, "-".repeat(77), text || `(No licence file ships with this package. Its package.json declares ${licence}.)`);
  }
  return { text: `${parts.join("\n")}\n`, missing };
}

const { text, missing } = render();
if (process.argv.includes("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current !== text) {
    console.error("frontend/public/third-party-notices.txt is out of date. Run: node scripts/generateFrontendNotices.mjs");
    process.exit(1);
  }
  console.log("third-party notices are up to date");
} else {
  fs.writeFileSync(OUT, text);
  console.log(`wrote ${path.relative(ROOT, OUT)} (${text.length} bytes)${missing.length ? `; no licence file in: ${missing.join(", ")}` : ""}`);
}
